spring:
  codec:
    max-in-memory-size: 20MB
  datasource:
    url: jdbc:mysql://127.0.0.1:8000/demo_test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        allowMultiQueries: true
        characterEncoding: UTF-8
        serverTimezone: Asia/Shanghai
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      USE_LONG_FOR_INTS: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.db_structure_naming_strategy: legacy
axon:
  serializer:
    events: jackson
    messages: jackson
    general: jackson
